[project]
name = "reccmp"
dynamic = ["classifiers", "dependencies", "license", "scripts", "version"]
requires-python = ">= 3.10"

[flake8]
max-line-length = 120


[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["ghidra", "ghidra.*"]
ignore_missing_imports = true
