name: Install

on: [push, pull_request]

jobs:
  install:
    name: 'Test reccmp install'
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install reccmp
      shell: bash
      run: |
        pip install .