name: Download legobin

on:
  workflow_call:

jobs:
  lego:
    runs-on: ubuntu-latest
    steps:

    - name: Cache original binaries
      id: cache-lego
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: legobin
        key: legobin

    - name: Download original island binaries
      if: ${{ !steps.cache-lego.outputs.cache-hit }}
      run: |
        wget https://legoisland.org/download/CONFIG.EXE --directory-prefix=legobin
        wget https://legoisland.org/download/ISLE.EXE --directory-prefix=legobin
        wget https://legoisland.org/download/LEGO1.DLL --directory-prefix=legobin

  skifree:
    runs-on: ubuntu-latest
    steps:

    - name: Cache original binaries
      id: cache-skifree
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: skifree
        key: skifree

    - name: Download original ski binaries
      if: ${{ !steps.cache-skifree.outputs.cache-hit }}
      run: |
        wget https://archive.org/download/win3_SKIFREE/SKIFREE.ZIP
        unzip -d skifree SKIFREE.ZIP
