name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install reccmp
      shell: bash
      run: |
        pip install .

    - name: Create HTML file
      shell: bash
      working-directory: ./webui
      run: |
        reccmp-aggregate --samples ./testdata.json ./testdata.json --html ./index.html

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      working-directory: ./webui
      run: |
        npm ci

    - name: Install Playwright Browsers
      working-directory: ./webui
      run: |
        npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./webui
      run: |
        npm run e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: webui/playwright-report/
        retention-days: 30
