name: Test

on: [push, pull_request]

jobs:
  fetch-deps:
    name: Prepare sample binary files
    uses: ./.github/workflows/binfiles.yml

  test:
    name: '${{ matrix.platform.name }} ${{ matrix.python-version }}'
    runs-on: ${{ matrix.platform.os }}

    # TODO: experimental
    container:
      # TODO: try a newer one if this works well
      image: blacktop/ghidra:11.4.2-alpine

    needs: fetch-deps

    strategy:
      fail-fast: false
      matrix:
#        python-version: ["3.10", "3.11", "3.12", "3.13"]
        platform:
#          - { name: 'Windows', os: 'windows-latest' }
          - { name: 'Linux',   os: 'ubuntu-latest' }

    steps:
    - uses: actions/checkout@v4

    # Experiment: disabled (fails in container)
    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ matrix.python-version }}
    #     cache: 'pip'

    - name: Install python
      shell: bash
      run: |
        apk add python3 py3-pip
        python3 -m venv .venv


    - name: Restore sample binaries
      id: cache
      uses: actions/cache/restore@v3
      with:
        enableCrossOsArchive: true
        path: binfiles
        key: binfiles

    - name: Install python libraries
      shell: bash
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt -r requirements-tests.txt

    - name: Run unit tests
      shell: bash
      run: |
        source .venv/bin/activate
        pytest . --binfiles=binfiles --require-binfiles